// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductOrder.Models;

#nullable disable

namespace ProductOrder.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductOrder.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "O001",
                            Address = "HCM",
                            Name = "Van A",
                            Phone = "113"
                        },
                        new
                        {
                            Id = "O002",
                            Address = "NA",
                            Name = "Van B",
                            Phone = "114"
                        },
                        new
                        {
                            Id = "O003",
                            Address = "DN",
                            Name = "Van C",
                            Phone = "115"
                        });
                });

            modelBuilder.Entity("ProductOrder.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductName");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = "O001",
                            ProductName = "Pepsi",
                            Price = 3,
                            Quantity = 10
                        },
                        new
                        {
                            OrderId = "O002",
                            ProductName = "CoCa",
                            Price = 5,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = "O003",
                            ProductName = "7Up",
                            Price = 8,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ProductOrder.Models.OrderDetail", b =>
                {
                    b.HasOne("ProductOrder.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProductOrder.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
