// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pretest2.Models;

#nullable disable

namespace Pretest2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pretest2.Models.tbNews", b =>
                {
                    b.Property<string>("NewsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateOfPublish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsId");

                    b.ToTable("tbNews");

                    b.HasData(
                        new
                        {
                            NewsId = "new1",
                            DateOfPublish = "4/1/2024",
                            NewsContent = "ncc"
                        },
                        new
                        {
                            NewsId = "new2",
                            DateOfPublish = "5/1/2024",
                            NewsContent = "ndb"
                        },
                        new
                        {
                            NewsId = "new3",
                            DateOfPublish = "6/1/2024",
                            NewsContent = "dmm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
